### ISSUE TITLE
set-output deprecation annotation thrown during action execution

### ISSUE THREAD

**Issue by pzim** [WyriHaximus/github-action-wait-for-status#136] opened 2023-05-10 02:13 UTC
I've been fixing all the `set-output` deprecation warnings for all of my github workflows, the last of which is one being thrown when running the `wait-for-status` action:
![image](https://github.com/WyriHaximus/github-action-wait-for-status/assets/737760/fdb3e427-b145-4068-8620-2d49300623f3)

According to https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ `set-output` will not longer work. 

reference to the line of code here: https://github.com/WyriHaximus/github-action-wait-for-status/blob/master/wait.php#L50

I tried submitting a PR, but getting a 403 when attempting to push my branch. Would appreciate any help or guidance you can provide on how to proceed. Thanks

**Comment by WyriHaximus** [comment] 2023-05-22 12:20
> I've been fixing all the `set-output` deprecation warnings for all of my github workflows, the last of which is one being thrown when running the `wait-for-status` action: ![image](https://user-images.githubusercontent.com/737760/237260312-fdb3e427-b145-4068-8620-2d49300623f3.png)

Same, finding them in lots of different places scattered everywhere. So also started to implement reusable workflows to combat that. However it still needs to be fixed here.

> According to https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ `set-output` will not longer work.

Yup, and checking for the page it seems they have postponed the removal by the end of this month. However I also just want to have it fixed.

> reference to the line of code here: https://github.com/WyriHaximus/github-action-wait-for-status/blob/master/wait.php#L50

Already have https://github.com/WyriHaximus/github-action-wait-for-status/pull/131 open for it.

> I tried submitting a PR, but getting a 403 when attempting to push my branch. Would appreciate any help or guidance you can provide on how to proceed. Thanks

And tried fixing that in https://github.com/WyriHaximus/github-action-wait-for-status/pull/132 but running into the same issue.

So there are two options:

1. Yolo merge #131 as it should work. release it, and then finish #132
2. Fix #132, and use that to confirm #131 works

Preferring going the second route because I do suspect something in the API has changed.

**Comment by WyriHaximus** [comment] 2023-05-25 06:28
Hey @pzim, you might have noticed I released a new version a few days ago but that the warning hasn't gone away yet. This is because the v1 tag is still pointing at Docker Hub for the OCI image instead of the GitHub Container Registry. I'll swap that tag around later today, after I figured out how to do that without downtime :sweat_smile: .

**Comment by WyriHaximus** [comment] 2023-06-01 19:41
Hey @pzim just confirmed that the `v1` Git tag is now pointing at GHCR.io and has the updated output method. Will close this issue as it's resolved. Feel free to comment or reopen it if somehow the issue persists for you.

**Closed** 2023-06-01 19:42 UTC
