### ISSUE TITLE
Uncaught Throwable TypeError: Argument 1 null given

### ISSUE THREAD

**Issue by zeisss** [WyriHaximus/github-action-wait-for-status#3] opened 2020-01-31 13:45 UTC
I am trying to make my release workflow (ran for tags) wait for my normal workflow (ran for pushes), so I don't need to copy and paste the build and unittest steps to the second pipeline.

Thus I added the wait-for-status check:
```
    - name: 'Wait for status checks'
      uses: "WyriHaximus/github-action-wait-for-status@0.1.0"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
```

But I received an uncaught error:
```
[2020-01-31 13:41:26.712694] wait.DEBUG: Looking up owner: stormforger
[2020-01-31 13:41:28.013838] wait.DEBUG: Looking up repository: hail
[2020-01-31 13:41:28.314160] wait.DEBUG: Locating commit: c6e3c40947b44bb167b2f38f144bb479f37e0f5d
[2020-01-31 13:41:28.709103] wait.DEBUG: Locating checks:
[2020-01-31 13:41:29.390790] wait.ERROR: Uncaught Throwable TypeError: "Argument 1 passed to {closure}() must be an instance of ApiClients\Client\Github\Resource\Async\Repository\Commit, null given, called in /workdir/vendor/react/promise/src/FulfilledPromise.php on line 25" at /workdir/wait.php line 70
```

The step status was green and the build continued.

So my questions are:
1) Is it intended for uncaught errors NOT to abort the build?
2) Do I need to change something about my config or is the uncaught error a bug?

**Comment by WyriHaximus** [comment] 2020-02-02 21:00
The answer to your questions is both no. This is a bug in specific situations where the commit with the checks and statuses can't be found. (Either non are there or due to race-conditions.) Currently working on a rewrite that is extensively tested for cases like these.

**Comment by tabossert** [comment] 2020-03-20 19:22
Getting same issue every time action is run, anything I can do now while you are working on the rewrite?

**Comment by WyriHaximus** [comment] 2020-03-22 22:21
@tabossert Not yet, currently working on this in the evening, to get rid of this error, but also making it more resilient to errors in the future. Should have a PR up tomorrow, maybe even today

**Comment by WyriHaximus** [comment] 2020-04-04 22:08
Work in Progress PR is up #5

**Comment by WyriHaximus** [comment] 2020-04-06 21:25
Right so had some good progress today, full success and failure flows are working. Also adding improved error messages so it's going to be a lot more clear what's going on:

![image](https://user-images.githubusercontent.com/147145/78606323-692bef00-785d-11ea-9d19-eacff0d7485f.png)
![image](https://user-images.githubusercontent.com/147145/78606425-98daf700-785d-11ea-80b7-5c0e9f49249b.png)

**Comment by WyriHaximus** [comment] 2020-04-09 16:08
@zeisss @tabossert Do either of you have a public commit somewhere where you ran into issue? Like to test against it to be sure. Focussing on getting basic testing this evening and tomorrow so the PR can be merged and released before next week

**Comment by zeisss** [comment] 2020-04-12 15:59
Sorry, this was on a private repository.

**Comment by WyriHaximus** [comment] 2020-04-12 16:25
> Sorry, this was on a private repository. 

Yeah tried with the details from the initial post. The good news is that running it against this PR  using master shows the issue you report, the even better news is that using this branch instead works.

**Comment by WyriHaximus** [comment] 2020-04-25 12:51
So everything works as intended, but found out today that sometimes it hits the API rate limit (been hunting some odd behavior down for a few nights now), will add some extra information and configuration on how to deal with that when it occurs.

**Closed** 2020-04-26 10:35 UTC

**Comment by tobiasdiez** [comment] 2020-07-07 18:08
I just run into this error (with action version 0.1.0): https://github.com/JabRef/JabRef-Browser-Extension/pull/187/checks?check_run_id=846743461

Do you have a ETA when the new version of this action is released?

**Comment by WyriHaximus** [comment] 2020-07-08 12:48
@tobiasdiez currently doing the finishing touches for v1 now, release either today or tomorrow.

**Comment by WyriHaximus** [comment] 2020-07-08 18:55
@tobiasdiez You can now use `@v1`. Ported some extra checks back from other actions, and also made some final bug fixes

**Comment by tobiasdiez** [comment] 2020-07-08 20:39
Perfect! Thanks a lot.
